# Generated by Django 5.2.7 on 2026-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('guest_count', models.PositiveSmallIntegerField(default=1, verbose_name='Mehmonlar soni')),
                ('status', models.CharField(choices=[('yes', 'Ha, kelaman'), ('no', 'Kela olmayman'), ('maybe', 'Ehtimol')], default='yes', max_length=10, verbose_name='Javob')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
