# Generated by Django 5.2.7 on 2026-06-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Rasm')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Yorliq (masalan: EXTERIOR)')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Izoh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10, verbose_name='Vaqt (masalan: 18:00)')),
                ('event', models.CharField(max_length=150, verbose_name='Tadbir nomi')),
                ('icon', models.CharField(default='✦', max_length=10, verbose_name='Ikonka (emoji)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Dastur bandi',
                'verbose_name_plural': "To'y dasturi",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(default="Ulug'bek", max_length=100, verbose_name='Kuyov ismi')),
                ('bride_name', models.CharField(default='Malika', max_length=100, verbose_name='Kelin ismi')),
                ('wedding_date', models.DateField(verbose_name="To'y sanasi")),
                ('wedding_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('wedding_day_name', models.CharField(default='Chorshanba', max_length=30, verbose_name='Hafta kuni (UZ)')),
                ('ayat_text', models.TextField(default='"Va U ularning qalblarini birlashtirdi"', verbose_name='Oyat / Iqtibos matni')),
                ('ayat_ref', models.CharField(default='Al-Anfal, 63', max_length=60, verbose_name='Oyat manbasi')),
                ('invite_message', models.TextField(default="Sizlarni to'yimizga taklif etishdan juda xursandmiz.", verbose_name='Taklif matni')),
                ('invite_sub', models.TextField(default='Ushbu quvonchli kunimizni siz bilan birga nishonlashni istaymiz.', verbose_name="Taklif qo'shimcha matni")),
                ('venue_name', models.CharField(default='"Baxtiyor" restorani', max_length=200, verbose_name="To'yxona nomi")),
                ('venue_address', models.TextField(default="Toshkent viloyati, Qibray tumani, Olmazor ko'chasi, 72", verbose_name='Manzil')),
                ('venue_phone', models.CharField(blank=True, max_length=30, verbose_name="To'yxona telefon")),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps havolasi')),
                ('yandex_maps_url', models.URLField(blank=True, verbose_name='Yandex Xarita havolasi')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps embed URL (iframe uchun)')),
                ('cover_bg', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Cover orqa fon rasmi')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Hero orqa fon rasmi')),
                ('invitation_bg', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name="Taklif bo'limi orqa fon rasmi")),
            ],
            options={
                'verbose_name': "To'y sozlamalari",
                'verbose_name_plural': "To'y sozlamalari",
            },
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='message',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('yes', 'Ha, kelaman'), ('no', 'Kela olmayman')], default='yes', max_length=10, verbose_name='Javob'),
        ),
    ]
